version: "3.8"
services:
  rest:
    container_name: rest
    build:
      context: .
      dockerfile: build/rest/Dockerfile
      target: dev
    volumes:
    - .:/app:rw,delegated
    networks:
    - my_network
    ports:
    - 8000:8000
    - 2345:2345
  grpc:
    container_name: grpc
    build:
      context: .
      dockerfile: build/grpc/Dockerfile
      target: dev
    volumes:
    - .:/app:rw,delegated
    networks:
    - my_network
    ports:
    - 9000:9000
    - 2346:2346


networks:
  my_network:
    name: my_network
