timezone: "Asia/Makassar"
shutdown_timeout: 10s

rest:
  host: 0.0.0.0
  port: 8000

grpc:
  host: 0.0.0.0
  port: 9000

database:
  postgres:
    host: localhost
    port: 6969
    user: root
    password: root
    database: root
